name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python v3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pycodestyle
    - name: Analysing the code with pylint
      run: |
        pylint src
        pylint tests
    - name: Analysing the code with pycodestyle
      run: |
        pycodestyle src
        pycodestyle tests
  # test: comes next
